name: bifrost_node
description: Bifrost node

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.8.beta <3.0.0"


dependencies:
  args: ^2.3.1
  fixnum:
  fpdart:
  rational:
  topl_protobuf:
    path: ../../../protobuf-specs/build/dart
  bifrost_minting:
    path: ../minting
  bifrost_consensus:
    path: ../consensus
  bifrost_common:
    path: ../common
  bifrost_codecs:
    path: ../codecs
  bifrost_grpc:
    path: ../grpc
  bifrost_p2p:
    path: ../p2p
  bifrost_crypto:
    path: ../crypto
dev_dependencies:    
  build_runner: ^1.10.3
