version: "3.3"

services:
  bifrost:
    build: ../../../../target/docker/stage
    ports:
      - 9085:9085
    command: -s test --apiKeyHash As3ZuwnL9LpoW3wz8HoDpHtZqJ4dhPFFnv87GYrnCYKj

  assistant:
    image: toplprotocol/postman-integration-testing-server
    ports:
      - 3000:3000
    volumes:
      - ./keyfile.json:/mnt/keyfile.json
    command:
      node ./bin/www /mnt/keyfile.json test http://bifrost:9085 test private
    links:
      - bifrost

  postman:
    image: postman/newman:latest
    depends_on:
      - bifrost
      - assistant
    volumes:
      - ./postman_env.json:/mnt/postman_env.json
      - ./wait-for-it.sh:/mnt/wait-for-it.sh
    links:
      - assistant
      - bifrost
    entrypoint:
      sh
      /mnt/wait-for-it.sh http://bifrost:9085 --
      newman
      run https://www.getpostman.com/collections/3468057a1009eebc86bf
      -e /mnt/postman_env.json
