{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "bifrost.fullname" . }}-role
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "pods/status", "events", "secrets", "configmaps", "serviceaccounts", "namespaces"]
    verbs: ["get", "list", "watch", "update", "patch", "delete"]
{{- end }}