{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "bifrost.fullname" . }}-rolebinding
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "bifrost.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "bifrost.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
