{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bifrost.serviceAccountName" . }}
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end }}
