package co.topl.crypto

import co.topl.attestation.Address
import co.topl.utils.ValidGenerators
import org.scalatest.matchers.should.Matchers
import org.scalatest.propspec.AnyPropSpec
import org.scalatestplus.scalacheck.{ScalaCheckDrivenPropertyChecks, ScalaCheckPropertyChecks}

import scala.util.{Failure, Success}

class KeySpec
  extends AnyPropSpec
    with ScalaCheckPropertyChecks
    with ScalaCheckDrivenPropertyChecks
    with ValidGenerators
    with Matchers {

  val password: String = stringGen.sample.get
  val messageByte: Array[Byte] = nonEmptyBytesGen.sample.get


  //TODO: Jing - Maybe generate the testing keyfiles in a separate directory?
  val address: Address = keyRing.generateKeyFile(password) match {
    case Success(addr) => addr
    case Failure(ex) => throw new Error(s"An error occurred while creating a new keyfile. $ex")
  }

  property("The randomly generated address from generateKeyFile should exist in keyRing") {
    keyRing.addresses.contains(address) shouldBe true
  }

  property("Once we lock the generated address, it will be removed from the secrets set in the keyRing") {
    keyRing.lockKeyFile(address.toString, password)
    /** There will be a warning if a key is already locked */
    keyRing.lockKeyFile(address.toString, password)

    keyRing.addresses.contains(address) shouldBe false
  }

  property("Once unlocked, the address will be accessible from the keyRing again") {
    keyRing.unlockKeyFile(address.toString, password)
    /** There will be a warning if a key is already unlocked */
    keyRing.unlockKeyFile(address.toString, password)

    keyRing.addresses.contains(address) shouldBe true
  }

  property("LookupPublickKey should return the correct public key to the address") {
    keyRing.lookupPublicKey(address).get.address shouldEqual address
  }

  property("The proof generated by signing the message Bytes with address should be valid") {
    val proof = keyRing.signWithAddress(address, messageByte).get
    val prop = keyRing.lookupPublicKey(address).get
    proof.isValid(prop, messageByte)
  }

  //TODO: Jing - test importPhrase
}
