name: bifrost_p2p
description: Bifrost peer-to-peer

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.8.beta <3.0.0"


dependencies:
  fpdart: ^0.3.0
  topl_protobuf:
    path: ../../../protobuf-specs/build/dart
  bifrost_grpc:
    path: ../grpc
  bifrost_crypto:
    path: ../crypto

dev_dependencies:    
  build_runner: ^1.10.3
