name: bifrost_minting
description: Bifrost minting

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.8.beta <3.0.0"


dependencies:
  async: ^2.10.0
  fpdart: ^0.3.0
  topl_protobuf:
    path: ../../../protobuf-specs/build/dart
  bifrost_common:
    path: ../common
  bifrost_crypto:
    path: ../crypto
  bifrost_codecs:
    path: ../codecs
dev_dependencies:    
  build_runner: ^1.10.3
