name: bifrost_minting
description: Bifrost minting

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.8.beta <3.0.0"


dependencies:
  async: ^2.10.0
  rational: ^2.2.2
  fpdart: ^0.3.0
  logging:
  topl_protobuf:
    path: ../../../protobuf-specs/build/dart
  bifrost_common:
    path: ../common
  bifrost_crypto:
    path: ../crypto
  bifrost_codecs:
    path: ../codecs
  bifrost_consensus:
    path: ../consensus
dev_dependencies:    
  build_runner: ^2.3.3
  test: ^1.24.0
  mockito: ^5.4.0
  convert: ^3.1.1
