package co.topl.genus.ops

/**
 * This package contains a set of extensions operations to types and companions defined in protobuf.
 * Since the code for these types is generated by the protobuf compiler, we will not be able to modify the
 * source types directly to add new methods. Instead, any new methods added to protobuf types or companions should be
 * through this package.
 */
package object protobufops {

  trait Implicits
      extends BlocksQueryStreamReqOps.ToBlocksQueryStreamReqOps
      with BlocksQueryStreamResCompanionOps.ToBlocksQueryStreamResCompanionOps
      with BlocksSubscriptionResCompanionOps.ToBlocksSubscriptionResCompanionOps
      with CreateBlocksSubscriptionReqOps.ToCreateBlocksSubscriptionReqOps
      with CreateTxsSubscriptionReqOps.ToCreateTxsSubscriptionReqOps
      with QueryBlocksReqOps.ToQueryBlocksReqOps
      with QueryBlocksResCompanionOps.ToQueryBlocksResCompanionExtensions
      with QueryTxsReqOps.ToQueryTxsReqOps
      with QueryTxsResCompanionOps.ToQueryTxsResCompanionOps
      with TxsQueryStreamReqOps.ToTxsQueryStreamReqOps
      with TxsQueryStreamResCompanionOps.ToTxsQueryStreamResCompanionOps
      with TxsSubscriptionResCompanionOps.ToTxsSubscriptionResCompanionOps

  object implicits extends Implicits
}
