name: bifrost_crypto
description: Bifrost crypto

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.8.beta <3.0.0"


dependencies:
  cryptography: ^2.0.5
  fpdart: ^0.3.0
  fixnum:
  topl_protobuf:
    path: ../../../protobuf-specs/build/dart
dev_dependencies:    
  build_runner: ^1.10.3
