#!/bin/bash
declare -a arr=("BifrostHistory" "BifrostNodeViewHolder" "BifrostLocalInterface" "BifrostApp" "Forger" "ScorexLogging" "DifficultyBlockValidator" "PeerSynchronizer" "SwaggerDocService" "ScorexObserver" "PolyTransferGenerator" "NetworkController" "PeerManager" "PeerConnectionHandler")

# Get full diagram
./scaladiagrams -l -s ~/git/bifrost/src/main/scala/bifrost/ | dot -Tsvg > ~/git/bifrost/docs/scaladiagrams/projectBifrost.svg

# Get partial diagrams
for i in "${arr[@]}"
do
   ./scaladiagrams -l -s ~/git/bifrost/src/main/scala/bifrost/ -p "$i" | dot -Tsvg > ~/git/bifrost/docs/scaladiagrams/$i.svg
done


