// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "org.scala-js" % "scalajs-library_2.12" % "0.6.18"
)
// LIBRARY_DEPENDENCIES_HASH 86b62ce04f3ccbcd2613c9eee8414bebb60122d3
