skip-check:
  - CKV_K8S_14 # Ignore since default should just pull latest tag, users will override specific version: https://docs.bridgecrew.io/docs/bc_k8s_13.
  - CKV_K8S_43 # Ignore since users will override the default Docker image: https://docs.bridgecrew.io/docs/bc_k8s_39.
  - CKV_K8S_21 # Ignore since users will override the namespace when deploying with Helm: https://docs.bridgecrew.io/docs/bc_k8s_20.
  - CKV_K8S_40 # TODO: Remove this once the Bifrost Docker image is using a high UID.
evaluate-variables: true
framework: all
output: cli
quiet: true
