name: bifrost_common
description: Bifrost common

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.8.beta <3.0.0"


dependencies:
  fpdart: ^0.3.0
  topl_protobuf:
    path: ../../../protobuf-specs/build/dart
dev_dependencies:    
  build_runner: ^1.10.3
