name: Publish Docker Image

on:
  workflow_call:
    inputs:
      remote-repository:
        description: 'Preserve project cache between new runs.'
        default: "us-central1-docker.pkg.dev/topl-shared-project-dev/topl-artifacts-dev/"
        required: false
        type: string

jobs:
  publish_docker_image:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_OIDC_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_OIDC_SERVICE_ACCOUNT_EMAIL }}
        
      - name: Auth Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Set up gcloud
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Stage Docker Image
        run: sbt nodeTetra/docker:publishLocal

      - name: Tag and push image to remote registry 
        run: |
          docker tag $(docker images toplprotocol/bifrost-node-tetra --format "{{.ID}}" | head -n 1) ${{ inputs.remote-repository }}bifrost-node-tetra:$(docker images toplprotocol/bifrost-node-tetra --format "{{.Tag}}" | head -n 1)
          docker push --all-tags ${{ inputs.remote-repository }}bifrost-node-tetra
