name: Validate Helm Chart

on:
  workflow_call:
    inputs:
      target-os:
        description: 'List of operating systems to build on.'
        default: 'ubuntu-latest'
        required: false
        type: string

jobs:
  validate_helm:
    name: Validate Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Need full history to update last modified time.
          submodules: true

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: helm/
          config_file: helm/.checkov.yaml
