name: Ad hoc Test

on:
  workflow_dispatch:
    inputs:
      debug-logging-enabled:
        description: 'Enable Debug Logging?'
        required: true
        default: false
        type: boolean

jobs:
  sbt-build:
    uses: ./.github/workflows/_sbt_build.yml
    with:
      preserve-cache-between-runs: true
  sbt-integration-tests:
    uses: ./.github/workflows/_sbt_integration_tests.yml
    needs: [sbt-build]
    with:
      preserve-cache-between-runs: true
  sbt-byzantine-tests:
    uses: ./.github/workflows/_sbt_byzantine_tests.yml
    needs: [sbt-build]
    with:
      preserve-cache-between-runs: true
      debug-logging-enabled: ${{ inputs.debug-logging-enabled }}
  publish-test-results:
    uses: ./.github/workflows/_publish_test_results.yml
    needs: [sbt-build, sbt-integration-tests, sbt-byzantine-tests]
    if: always()
