name: Postman Integration Tests

on:
  pull_request:
    branches: [dev, main, release-*, rc-*]

jobs:

  build:
    name: Run Integration Tests

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Bifrost
      uses: actions/checkout@v2

    - name: Setup Java and Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: graalvm-ce-java11@21.1.0
        
    - name: Stage Docker Image
      run: sbt bifrost/docker:stage

    - name: Integration Tests
      run: docker-compose -f ./node/src/it/resources/postman-tests/docker-compose.yml up --exit-code-from postman
      
