{
 "title": "Bifrost Monitor",
 "description": "Tools for monitoring the behavior of the Bifrost application",
 "tags": [
  "kamon",
  "akka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "SHOW TAG VALUES WITH KEY = \"instance\""
   },
   {
    "name": "class",
    "label": "Actor path",
    "query": "SHOW TAG VALUES WITH KEY = class"
   }
  ]
 },
 "panels": [
  { "title": "Akka actors and system", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Relative mailbox size across actors",
   "type": "graph",
   "description": "The shows the number of messages processed by each actor normalized by the total number of messages. This metric is useful for determining which actors are receiving the most messages with the system.",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "akka.actor.mailbox-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "class", "operator": "=~", "value": "/^$class$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Actors",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "akka.system.active-actors",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Unhandled Messages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "akka.system.unhandled-messages",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Processed Messages",
   "type": "singlestat",
   "description": "The number of messages that were processed in the latest time interval.",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "akka.system.processed-messages",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "tracked", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Occurrence of time spent processing messages for NodeViewHolder (ms)",
   "type": "graph",
   "description": "The distribution of processing time for the NodeViewHolder over the entire time of interest. ",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Counts" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "akka.actor.processing-time",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "class", "operator": "=", "value": "bifrost.NodeViewHolder" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "akka.actor.errors",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "class", "operator": "=~", "value": "/^$class$/" }
     ]
    }
   ]
  },
  {
   "title": "Dead Letters",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "akka.system.dead-letters",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Average number of processed messages",
   "type": "stat",
   "description": "The average and standard deviation of processed messages over the specified time period",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 6 },
   "targets": [
    {
     "measurement": "akka.system.processed-messages",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       }
      ]
     ],
     "tags": [
      { "key": "tracked", "operator": "=", "value": "true" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Occurrence of time spent queued in a mailbox (us)",
   "type": "graph",
   "description": "The distribution of queue time by actors over the entire time of interest. This is useful to show which actors may be taking a long time to get to processing messages. ",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Counts" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "akka.actor.time-in-mailbox",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "class", "operator": "=~", "value": "/^$class$/" }
     ]
    }
   ]
  },
  {
   "title": "Occurrence of time spent processing messages (us)",
   "type": "graph",
   "description": "The distribution of processing time by actors over the entire time of interest. This is useful to show which actors may be taking a long time to process messages. ",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Counts" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "akka.actor.processing-time",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "class", "operator": "=~", "value": "/^$class$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 22 },
   "content": "### Number of processed messages by actor\n---\nShows the total number of processed messages for each actor in each interval\n\n#### Metric details\n* Name: akka.group.processing-time\n* Type: timer\n* Description: Tracks the time taken for a member actor to process the receive function.\n\n\n"
  },
  {
   "title": "Number of processed messages by actor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Number of messages" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "akka.actor.processing-time",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "class", "operator": "=~", "value": "/^$class$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 32 },
   "content": "### Total time spent processing messages\n---\nShows the total time spent processing messages for each time interval.\n\n**NOTE:** The Y-axis is log-scaled\n\n#### Metric details\n* Name: akka.group.processing-time \n* Type: timer\n* Description: Tracks the time taken for a member actor to process the receive function.\n\n\n\n"
  },
  {
   "title": "Total time spent processing messages",
   "type": "graph",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 32 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "akka.actor.processing-time",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "class", "operator": "=~", "value": "/^$class$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 43 },
   "content": "### Average time to process a message\n---\nShows the mean time to process messages for each actor. This is computed by summing the total time spent processing messages and dividing by the total number of messages processed.\n\n**NOTE:** Y-axis is log scaled\n\n#### Metric details \n* Name: akka.group.processing-time\n* Type: timer\n* Description: Tracks the time taken for a member actor to process the receive function.\n\n\n\n"
  },
  {
   "title": "Average time to process a message",
   "type": "graph",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 43 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "akka.actor.processing-time",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "class", "operator": "=~", "value": "/^$class$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 54 },
   "content": "### Average time messages are queud in mailboxes by actor\n---\nShows the mean time to dequeue a message for processing for each actor. This is computed by summing the total time spent by dequeued messages in the mailbox and dividing by the total number of dequeued messages.\n\n#### Metric details\n* Name: akka.actor.time-in-mailbox\n* Type: timer\n* Description: Tracks the time since the instant a message is enqueued in an Actor's mailbox until it is dequeued for processing.\n"
  },
  {
   "title": "Average time a message is in a mailbox",
   "type": "graph",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 54 },
   "yaxes": [
    { "format": "ns", "label": "Time in mailbox" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "akka.actor.time-in-mailbox",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "class", "operator": "=~", "value": "/^$class$/" }
     ]
    }
   ]
  },
  { "title": "Akka executor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Executor threads minimum",
   "type": "gauge",
   "description": "executor.threads.min gauge\nTracks executor minimum number of Threads.\n\nexecutor.threads.max gauge\nTracks executor maximum number of Threads.",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 66 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "executor.threads.min",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Executor threads minimum",
   "type": "gauge",
   "description": "executor.threads.min gauge\nTracks executor minimum number of Threads.\n\nexecutor.threads.max gauge\nTracks executor maximum number of Threads.",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 66 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "executor.threads.max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Executor tasks",
   "type": "graph",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "executor.tasks.submitted",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "executor.tasks.completed",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Dispatcher Time in Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "executor.time-in-queue",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "executor.time-in-queue",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ],
      [
       { "params": [ "min" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "DIspatcher active threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "executor.threads.active",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Dispatcher size of queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "executor.queue-size",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ],
      [
       { "params": [ "min" ], "type": "field" }
      ],
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "DIspatcher total threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "executor.threads.total",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Akka HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "collapsed": true,
   "panels": [
    {
     "title": "Http Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "http.status_code" ], "type": "tag" }
       ],
       "measurement": "http.server.requests",
       "select": [
        [
         { "params": [ "count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "HTTP connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "yaxes": [
      { "format": "none", "label": "Connections" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "interface" ], "type": "tag" }
       ],
       "measurement": "http.server.connection.open",
       "select": [
        [
         { "params": [ "min" ], "type": "field" }
        ],
        [
         { "params": [ "max" ], "type": "field" }
        ],
        [
         { "params": [ "mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Server response size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "measurement": "http.server.response.size",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "JVM metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Memory pool - Committed",
   "type": "graph",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "pool" ], "type": "tag" }
     ],
     "measurement": "jvm.memory.pool.committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory pool - Free",
   "type": "graph",
   "gridPos": { "h": 16, "w": 7, "x": 7, "y": 96 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "pool" ], "type": "tag" }
     ],
     "measurement": "jvm.memory.pool.free",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory pool - Used",
   "type": "graph",
   "gridPos": { "h": 16, "w": 10, "x": 14, "y": 96 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "pool" ], "type": "tag" }
     ],
     "measurement": "jvm.memory.pool.used",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory - Commited",
   "type": "graph",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "region" ], "type": "tag" }
     ],
     "measurement": "jvm.memory.committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory - Free",
   "type": "graph",
   "gridPos": { "h": 16, "w": 7, "x": 7, "y": 112 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "region" ], "type": "tag" }
     ],
     "measurement": "jvm.memory.free",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory - Used",
   "type": "graph",
   "gridPos": { "h": 16, "w": 10, "x": 14, "y": 112 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "region" ], "type": "tag" }
     ],
     "measurement": "jvm.memory.used",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "jvm.threads.daemon",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "measurement": "jvm.threads.peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "measurement": "jvm.threads.total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 128 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "component" ], "type": "tag" }
     ],
     "measurement": "jvm.memory.allocation",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  { "title": "Host resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "mode" ], "type": "tag" }
     ],
     "measurement": "process.cpu.usage",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Process hiccups",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 137 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "measurement": "process.hiccups",
     "select": [
      [
       { "params": [ "min" ], "type": "field" }
      ],
      [
       { "params": [ "max" ], "type": "field" }
      ],
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 3, "x": 0, "y": 148 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "period" ], "type": "tag" }
     ],
     "measurement": "host.load.average",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Host memory usage",
   "type": "graph",
   "gridPos": { "h": 16, "w": 8, "x": 3, "y": 148 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "measurement": "host.memory.used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "measurement": "host.memory.free",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Host network activity",
   "type": "graph",
   "gridPos": { "h": 16, "w": 13, "x": 11, "y": 148 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "measurement": "host.network.data.read",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "measurement": "host.network.data.write",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Host CPU Usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 164 },
   "yaxes": [
    { "format": "short", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "mode" ], "type": "tag" }
     ],
     "measurement": "host.cpu.usage",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "bifrost@heisenberg" }
     ]
    }
   ]
  }
 ]
}